# Generated by Django 5.1.3 on 2024-11-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tarefas',
            table='tbl_tarefas',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='tbl_usuarios',
        ),
    ]
